### ISSUE TITLE
2つのコードの差分を表示できるようにしてほしい

### ISSUE THREAD

**Issue by nimon-2AC** [Haur514/InfiniteVariety_exp_frontend#10]
めっちゃ似てるコードを目grepするのは厳しい
diff表示のon/offができるとうれしい

**Comment by nimon-2AC** [comment]
Prismでは難しい
https://www.github.com/PrismJS/prism/discussions/3324#discussioncomment-2132563

**Comment by Haur514** [comment]
[prettydiff](https://prettydiff.com/)を使うのがいいのかなぁ，などと思っています．
これ使うにしても作業は地獄そうですが．．．

**Comment by nimon-2AC** [comment]
Prism をやめて Ace にして，[Ace-diff](https://github.com/ace-diff/ace-diff) を使うのが楽な気もします
そもそもやらないという選択も……
